-- DASH_CLUSTER_DATA: breakdowns dimensionais por política/safra
CREATE OR REPLACE TABLE `meli-bi-data.SBOX_CREDITSTC.DASH_CLUSTER_DATA` AS
WITH base AS (
  SELECT
    FORMAT_DATE('%Y-%m', FECHA_CONVERSAO) AS safra,
    CASE
      WHEN grupo_especial = 'BAU-' THEN 'micro_tc'
      WHEN UPPER(grupo_especial) LIKE '%MTC%' THEN 'micro_tc'
      ELSE 'tc_full'
    END AS segmento,
    CASE
      WHEN grupo_especial = 'BAU-' THEN 'BAU-'
      WHEN grupo_especial LIKE 'BAU-MTC SEGMENTOS PREFERENCIAIS%' OR grupo_especial LIKE 'N/A-MTC SEGMENTOS PREFERENCIAIS%' THEN 'BAU-MTC SEGMENTOS PREFERENCIAIS'
      WHEN grupo_especial LIKE 'BAU-MTC BAU%' OR grupo_especial LIKE 'N/A-MTC BAU%' THEN 'BAU-MTC BAU'
      WHEN REGEXP_CONTAINS(grupo_especial, r'\b9A\b') THEN 'BAU-9A SELLERS'
      WHEN REGEXP_CONTAINS(grupo_especial, r'\b8A\b') THEN 'BAU-8A SELLERS'
      WHEN REGEXP_CONTAINS(grupo_especial, r'\b5A\b') THEN 'BAU-5A SELLERS'
      WHEN REGEXP_CONTAINS(grupo_especial, r'\b6A\b') THEN 'BAU-6A SELLERS'
      WHEN grupo_especial LIKE 'Mar Aberto RTS%' THEN 'Mar Aberto RTS'
      WHEN grupo_especial LIKE 'Mar Aberto Async%' THEN 'Mar Aberto Async'
      WHEN grupo_especial LIKE 'BAU-BAU GRUPO%SIN CAMBIOS%' THEN 'BAU-BAU GRUPO 1y2 SIN CAMBIOS'
      WHEN grupo_especial LIKE 'BAU-BAU GRUPO%- UP%' THEN 'BAU-BAU GRUPO 1y2 UP'
      WHEN grupo_especial LIKE 'BAU-HEAVY USERS%' OR grupo_especial LIKE 'N/A-HEAVY USERS%' THEN 'BAU-HEAVY USERS'
      WHEN grupo_especial LIKE 'BAU-CARD TO CARD%' OR grupo_especial LIKE 'OPENFINANCE-CARD TO CARD%' THEN 'BAU-CARD TO CARD OPF'
      WHEN grupo_especial LIKE 'BAU-USUARIOS%VIP%' OR grupo_especial LIKE 'BAU-USUARIOS MARKETPLACE%' OR grupo_especial LIKE 'N/A-USUARIOS MARKETPLACE VIP%' OR grupo_especial LIKE 'N/A-USUARIOS VIP MARKETPLACE%' THEN 'BAU-USUARIOS MP VIP'
      WHEN grupo_especial LIKE 'TEST REACH-TEST NO ECOSISTEMATICOS%' OR UPPER(grupo_especial) LIKE 'AMPLIACI_N DE RATINGS-TEST NO ECOSISTEMATICOS%' THEN 'TEST REACH-TEST NO ECOSISTEMATICOS'
      WHEN grupo_especial LIKE 'TEST REACH-C1 THIN%' THEN 'TEST REACH-C1 THIN'
      WHEN grupo_especial LIKE 'TEST REACH-%B2 REPEATS%' THEN 'TEST REACH-B2 REPEATS'
      ELSE NULL
    END AS politica,
    IFNULL(RANGE_BUREAU, 'N/D') AS rb, IFNULL(RATING_TC, 'S/R') AS rt,
    IFNULL(FLAG_APP_ATIVO, 'N/D') AS fa, IFNULL(FLAG_SELLERS, 'N/D') AS fs, IFNULL(NISE_TAG, 'N/D') AS nt,
    SAFE_DIVIDE(TPV_D0, CCARD_GLOBAL_LIMIT_AMT_LC)*100 AS pct_d0,
    SAFE_DIVIDE(TPV_D7, CCARD_GLOBAL_LIMIT_AMT_LC)*100 AS pct_d7,
    SAFE_DIVIDE(TPV_D30, CCARD_GLOBAL_LIMIT_AMT_LC)*100 AS pct_d30,
    DEUDA_OVER6_MOB1, DEUDA_MOB1, DEUDA_OVER15_MOB2, DEUDA_MOB2, DEUDA_OVER30_MOB3, DEUDA_MOB3
  FROM `meli-bi-data.SBOX_CREDITSTC.0_TPV_PRIMEIRO_USO_TC_MP_POST_ADQ`
  WHERE FECHA_CONVERSAO >= '2025-04-01' AND CCARD_GLOBAL_LIMIT_AMT_LC > 0
)
SELECT
  safra, segmento, politica, dim_nome, dim_val,
  COUNT(*) AS cl,
  ROUND(AVG(pct_d0), 1) AS d0, ROUND(AVG(pct_d7), 1) AS d7, ROUND(AVG(pct_d30), 1) AS d30,
  ROUND(AVG(IF(pct_d0  >= 80, 1, 0))*100, 1) AS u0,
  ROUND(AVG(IF(pct_d30 >= 80, 1, 0))*100, 1) AS u30,
  ROUND(SAFE_DIVIDE(SUM(DEUDA_OVER6_MOB1),  SUM(DEUDA_MOB1)) *100, 2) AS over6,
  ROUND(SAFE_DIVIDE(SUM(DEUDA_OVER15_MOB2), SUM(DEUDA_MOB2))*100, 2)  AS over15,
  ROUND(SAFE_DIVIDE(SUM(DEUDA_OVER30_MOB3), SUM(DEUDA_MOB3))*100, 2)  AS over30
FROM base
CROSS JOIN UNNEST([
  STRUCT('RANGE_BUREAU' AS dim_nome, rb AS dim_val), STRUCT('RATING_TC', rt),
  STRUCT('FLAG_APP_ATIVO', fa), STRUCT('FLAG_SELLERS', fs), STRUCT('NISE_TAG', nt)
]) AS dims
WHERE politica IS NOT NULL
GROUP BY ALL ORDER BY safra, segmento, politica, dim_nome, dim_val
